import { logInfo } from '../utils/logger.mjs'
export class Migrations{
 constructor(db){this.db=db}
 async ensureTable(){await this.db.query(`CREATE TABLE IF NOT EXISTS schema_migrations (id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL UNIQUE,executed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)`)}
 async done(name,client=null){return Boolean(await this.db.queryOne('SELECT id FROM schema_migrations WHERE name=$1',[name],client))}
 async run(name,fn){if(await this.done(name))return;await this.db.transaction(async client=>{if(await this.done(name,client))return;await fn(client);await this.db.query('INSERT INTO schema_migrations(name) VALUES($1)',[name],client)});logInfo(`Migration aplicada: ${name}`)}
 async runAll(){await this.ensureTable();await this.run('001_initial',async c=>{
  const stmts=[
`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,phone TEXT NOT NULL UNIQUE,name TEXT NOT NULL,role TEXT NOT NULL,keyword_hash TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS media(id TEXT PRIMARY KEY,category TEXT NOT NULL,filename TEXT NOT NULL,mime_type TEXT NOT NULL,sha256 TEXT,data BYTEA NOT NULL,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS captains(id TEXT PRIMARY KEY,user_id TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,organization TEXT,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS scrims(id TEXT PRIMARY KEY,name TEXT NOT NULL,date TEXT NOT NULL,time TEXT NOT NULL,mode TEXT NOT NULL,max_teams INTEGER NOT NULL,entry_fee NUMERIC(10,2) NOT NULL DEFAULT 0,pix_key TEXT NOT NULL,drops INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'open',scoring_config JSONB NOT NULL DEFAULT '{}'::jsonb,disallow_duplicate_players BOOLEAN NOT NULL DEFAULT true,created_by TEXT,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS teams(id TEXT PRIMARY KEY,captain_id TEXT NOT NULL REFERENCES captains(id) ON DELETE CASCADE,name TEXT NOT NULL,logo_media_id TEXT REFERENCES media(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS registrations(id TEXT PRIMARY KEY,scrim_id TEXT NOT NULL REFERENCES scrims(id) ON DELETE CASCADE,team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,captain_id TEXT NOT NULL REFERENCES captains(id) ON DELETE CASCADE,team_name TEXT NOT NULL,players TEXT[] NOT NULL,player_keys TEXT[] NOT NULL,reserves TEXT[],logo_media_id TEXT NOT NULL REFERENCES media(id),slot INTEGER NOT NULL,status TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(scrim_id,slot),UNIQUE(scrim_id,team_id))`,
`CREATE TABLE IF NOT EXISTS payments(id TEXT PRIMARY KEY,registration_id TEXT NOT NULL REFERENCES registrations(id) ON DELETE CASCADE,proof_media_id TEXT NOT NULL REFERENCES media(id),status TEXT NOT NULL,amount NUMERIC(10,2) NOT NULL,duplicate BOOLEAN NOT NULL DEFAULT false,suspicious BOOLEAN NOT NULL DEFAULT false,duplicate_of_payment_id TEXT,duplicate_of_media_id TEXT,approved_by TEXT,approved_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS results(id TEXT PRIMARY KEY,scrim_id TEXT NOT NULL REFERENCES scrims(id) ON DELETE CASCADE,registration_id TEXT NOT NULL REFERENCES registrations(id) ON DELETE CASCADE,drop INTEGER NOT NULL,placement INTEGER NOT NULL,kills INTEGER NOT NULL,multiplier NUMERIC(6,3) NOT NULL,points NUMERIC(12,3) NOT NULL,screenshot_media_id TEXT NOT NULL REFERENCES media(id),ai_confidence NUMERIC(6,3),status TEXT NOT NULL,approved_by TEXT,approved_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(scrim_id,registration_id,drop))`,
`CREATE TABLE IF NOT EXISTS result_players(id TEXT PRIMARY KEY,result_id TEXT NOT NULL REFERENCES results(id) ON DELETE CASCADE,registration_id TEXT NOT NULL REFERENCES registrations(id) ON DELETE CASCADE,player_name TEXT NOT NULL,player_key TEXT NOT NULL,kills INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(result_id,player_key))`,
`CREATE TABLE IF NOT EXISTS rules(id TEXT PRIMARY KEY,content TEXT NOT NULL,created_by TEXT,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS bans(id TEXT PRIMARY KEY,phone TEXT NOT NULL,reason TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT true,created_by TEXT,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),expires_at TIMESTAMPTZ)`,
`CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,action TEXT NOT NULL,actor TEXT NOT NULL,target_type TEXT NOT NULL,target_id TEXT NOT NULL,changes JSONB,metadata JSONB,created_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS whatsapp_auth(id TEXT PRIMARY KEY,auth_key TEXT NOT NULL UNIQUE,auth_value JSONB NOT NULL,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS app_sessions(id TEXT PRIMARY KEY,phone TEXT NOT NULL UNIQUE,user_id TEXT,role TEXT,flow TEXT,step TEXT,temp_data JSONB,expires_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now())`,
`CREATE TABLE IF NOT EXISTS processed_messages(id TEXT PRIMARY KEY,message_id TEXT NOT NULL,sender_phone TEXT NOT NULL,kind TEXT,processed_at TIMESTAMPTZ DEFAULT now(),expires_at TIMESTAMPTZ NOT NULL,UNIQUE(message_id,sender_phone))`
]; for(const s of stmts)await this.db.query(s,[],c)
 });await this.run('002_indexes',async c=>{for(const s of [`CREATE INDEX IF NOT EXISTS idx_reg_scrim ON registrations(scrim_id)`,`CREATE INDEX IF NOT EXISTS idx_result_scrim ON results(scrim_id)`,`CREATE INDEX IF NOT EXISTS idx_media_hash ON media(sha256)`,`CREATE INDEX IF NOT EXISTS idx_processed_exp ON processed_messages(expires_at)`])await this.db.query(s,[],c)})}
}
export default Migrations
